services:
  - type: web
    name: history-rag-chainlit
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m chainlit run app.py -h --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_HOME
        value: /tmp/huggingface
